### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Chethan77jpg** [JamesRob123/EHP#2]
Due to the exam.net new update this code is no longer working for that. I would love to get the code first, if you make a code please send it to chethansrinivas055@gmail.com

**Comment by JamesRob123** [comment]
Thank you for the reply. I will try to fix the problem as quickly as possible and I will also make a video on how to temporary fix the problem. It should be up sometime today and I will send you an email when it is.

**Comment by Chethan77jpg** [comment]
Thank you sooo much
